---
# tasks file for web
- name: Install nginx package
  package:
    name: "{{ nginx_package_name }}"
    state: present

- name: Copy template file
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: 0644
  notify: Restart Nginx

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
    mode: 0644
  with_items: "{{ file_names }}"
  notify: Restart Nginx

- name: Enable Nginx service
  systemd:
    name: "{{ nginx_package_name }}"
    enabled: yes
    state: started